import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Car Maintainer App",
  description: "Generated by create next app",
};

export default function Head() {
  return (
    <>
      <title>{metadata.title}</title>
      <meta name="description" content={metadata.description} />
    </>
  );
}
