


// Use string literals for title/description to avoid type issues in <title> and <meta>
const TITLE = "Car Maintainer App";
const DESCRIPTION = "Generated by create next app";

export default function Head() {
  return (
    <>
      <title>{TITLE}</title>
      <meta name="description" content={DESCRIPTION} />
    </>
  );
}
